import frappe

from bandhu_app.bandhu_app.page.cad_form.cad_form import require_cad_access

STATE_DISTRICTS: dict[str, list[str]] = {
	"Bihar": [
		"Araria",
		"Arwal",
		"Aurangabad",
		"Banka",
		"Begusarai",
		"Bhagalpur",
		"Bhojpur",
		"Buxar",
		"Darbhanga",
		"East Champaran",
		"Gaya",
		"Gopalganj",
		"Jamui",
		"Jehanabad",
		"Kaimur",
		"Katihar",
		"Khagaria",
		"Kishanganj",
		"Lakhisarai",
		"Madhepura",
		"Madhubani",
		"Munger",
		"Muzaffarpur",
		"Nalanda",
		"Nawada",
		"Patna",
		"Purnia",
		"Rohtas",
		"Saharsa",
		"Samastipur",
		"Saran",
		"Sheikhpura",
		"Sheohar",
		"Sitamarhi",
		"Siwan",
		"Supaul",
		"Vaishali",
		"West Champaran",
	],
	"Uttar Pradesh": [
		"Agra",
		"Aligarh",
		"Ambedkar Nagar",
		"Amethi",
		"Amroha",
		"Auraiya",
		"Ayodhya",
		"Azamgarh",
		"Baghpat",
		"Bahraich",
		"Ballia",
		"Balrampur",
		"Banda",
		"Barabanki",
		"Bareilly",
		"Basti",
		"Bhadohi",
		"Bijnor",
		"Budaun",
		"Bulandshahr",
		"Chandauli",
		"Chitrakoot",
		"Deoria",
		"Etah",
		"Etawah",
		"Farrukhabad",
		"Fatehpur",
		"Firozabad",
		"Gautam Buddha Nagar",
		"Ghaziabad",
		"Ghazipur",
		"Gonda",
		"Gorakhpur",
		"Hamirpur",
		"Hapur",
		"Hardoi",
		"Hathras",
		"Jalaun",
		"Jaunpur",
		"Jhansi",
		"Kannauj",
		"Kanpur Dehat",
		"Kanpur Nagar",
		"Kasganj",
		"Kaushambi",
		"Kheri",
		"Kushinagar",
		"Lalitpur",
		"Lucknow",
		"Maharajganj",
		"Mahoba",
		"Mainpuri",
		"Mathura",
		"Mau",
		"Meerut",
		"Mirzapur",
		"Moradabad",
		"Muzaffarnagar",
		"Pilibhit",
		"Pratapgarh",
		"Prayagraj",
		"Raebareli",
		"Rampur",
		"Saharanpur",
		"Sambhal",
		"Sant Kabir Nagar",
		"Shahjahanpur",
		"Shamli",
		"Shrawasti",
		"Siddharthnagar",
		"Sitapur",
		"Sonbhadra",
		"Sultanpur",
		"Unnao",
		"Varanasi",
	],
	"Tamil Nadu": [
		"Ariyalur",
		"Chengalpattu",
		"Chennai",
		"Coimbatore",
		"Cuddalore",
		"Dharmapuri",
		"Dindigul",
		"Erode",
		"Kallakurichi",
		"Kanchipuram",
		"Kanniyakumari",
		"Karur",
		"Krishnagiri",
		"Madurai",
		"Mayiladuthurai",
		"Nagapattinam",
		"Namakkal",
		"Nilgiris",
		"Perambalur",
		"Pudukkottai",
		"Ramanathapuram",
		"Ranipet",
		"Salem",
		"Sivaganga",
		"Tenkasi",
		"Thanjavur",
		"Theni",
		"Thoothukudi",
		"Tiruchirappalli",
		"Tirunelveli",
		"Tirupathur",
		"Tiruppur",
		"Tiruvallur",
		"Tiruvannamalai",
		"Tiruvarur",
		"Vellore",
		"Viluppuram",
		"Virudhunagar",
	],
	"Assam": [
		"Baksa",
		"Bajali",
		"Barpeta",
		"Biswanath",
		"Bongaigaon",
		"Cachar",
		"Charaideo",
		"Chirang",
		"Darrang",
		"Dhemaji",
		"Dhubri",
		"Dibrugarh",
		"Dima Hasao",
		"Goalpara",
		"Golaghat",
		"Hailakandi",
		"Hojai",
		"Jorhat",
		"Kamrup",
		"Kamrup Metropolitan",
		"Karbi Anglong",
		"Kokrajhar",
		"Lakhimpur",
		"Majuli",
		"Morigaon",
		"Nagaon",
		"Nalbari",
		"Sivasagar",
		"Sonitpur",
		"South Salmara-Mankachar",
		"Tamulpur",
		"Tinsukia",
		"Udalguri",
		"West Karbi Anglong",
		"Sribhumi",
	],
	"Odisha": [
		"Angul",
		"Balangir",
		"Balasore",
		"Bargarh",
		"Bhadrak",
		"Boudh",
		"Cuttack",
		"Deogarh",
		"Dhenkanal",
		"Gajapati",
		"Ganjam",
		"Jagatsinghpur",
		"Jajpur",
		"Jharsuguda",
		"Kalahandi",
		"Kandhamal",
		"Kendrapara",
		"Keonjhar",
		"Khordha",
		"Koraput",
		"Malkangiri",
		"Mayurbhanj",
		"Nabarangpur",
		"Nayagarh",
		"Nuapada",
		"Puri",
		"Rayagada",
		"Sambalpur",
		"Subarnapur",
		"Sundargarh",
	],
	"West Bengal": [
		"Alipurduar",
		"Bankura",
		"Birbhum",
		"Cooch Behar",
		"Dakshin Dinajpur",
		"Darjeeling",
		"Hooghly",
		"Howrah",
		"Jalpaiguri",
		"Jhargram",
		"Kalimpong",
		"Kolkata",
		"Malda",
		"Murshidabad",
		"Nadia",
		"North 24 Parganas",
		"Paschim Bardhaman",
		"Paschim Medinipur",
		"Purba Bardhaman",
		"Purba Medinipur",
		"Purulia",
		"South 24 Parganas",
		"Uttar Dinajpur",
	],
}


@frappe.whitelist()
def get_districts(txt: str = "", state: str | None = None) -> list[str]:
	# Only the CAD registration form asks for these (cad_form.js:511, on native state change), so
	# it carries the same gate as the rest of that form instead of being open to every
	# authenticated user.
	require_cad_access()

	if not state:
		return []

	state_name = frappe.db.get_value("State", state, "state_name")

	if not state_name:
		return []

	districts = STATE_DISTRICTS.get(state_name, [])

	if txt:
		txt = txt.lower()
		districts = [district for district in districts if txt in district.lower()]

	return districts
